apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: final
type: Opaque
data:
  # These are base64 encoded values
  # To encode: echo -n "your_password" | base64
  mysql-root-password: <add your password here>  # cGFzc3dvcmQxMjM=
  mysql-user: <add your user here>  # root cm9vdA== 