apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: flask-app
        image: YOUR_ACCOUNT_ID.dkr.ecr.YOUR_REGION.amazonaws.com/clo835-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 81
        env:
        - name: DBHOST
          value: "mysql-service"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: DATABASE
          value: "employees"
        - name: BACKGROUND_IMAGE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BACKGROUND_IMAGE_URL
        - name: USER_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: USER_NAME
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AWS_REGION
        # AWS credentials as environment variables (replace with your actual values)
        - name: AWS_ACCESS_KEY_ID
          value: "YOUR_ACCESS_KEY_ID"
        - name: AWS_SECRET_ACCESS_KEY
          value: "YOUR_SECRET_ACCESS_KEY"
        - name: AWS_SESSION_TOKEN
          value: "YOUR_SESSION_TOKEN"  # Optional, leave empty if not using temporary credentials 