#service file
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: final
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 81
    protocol: TCP
  selector:
    app: flask-app