# Add webapp ReplicaSet with ECR image and secure MySQL connection

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset
  namespace: webapp-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: webapp
          image: 989788749302.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
          ports:
            - containerPort: 8080
          env:
            - name: DBHOST
              value: "mysql-service.mysql-ns.svc.cluster.local"
            - name: DBPORT
              value: "3306"
            - name: DBUSER
              value: "root"
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: mysql-password-secret
                  key: DBPWD
            - name: DATABASE
              value: "employees"
            - name: APP_COLOR
              value: "lime"
      imagePullSecrets:
        - name: ecr-registry-secret